server:
  port: 8082
  # DataSource Configspring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: admin

mybatis-plus:
      mapper-locations: classpath*:/mapper/**Mapper.xml   #?myabtis plus?mapper?xml???????