#seserver:
#    port: 8082
#  # DataSource Config
#  spring:
#      datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.12.128:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#
#mybatis-plus:
#      mapper-locations: classpath*:/mapper/**Mapper.xml   #myabtis plus的mapper的xml文件的扫描路径
#


server:
  port: 8082
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.128:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml